root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./bin/main ./cmd"
  bin = "./bin/main"
  full_bin = "./bin/main"
  include_ext = ["go"]
  exclude_dir = ["bin", "tmp", "vendor"]  
  log = "air.log"

[log]
  time = true
  file = "./tmp/air.log"

[delay]
  before = 200
  after = 200   

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
  use_polling = true

[screen]
  clear_on_rebuild = true
  keep_scroll = false