root = "/app"
tmp_dir = "tmp"

[build]
  pre_cmd = ["go mod edit -go=$(go version | awk '{print $3}' | tr -d 'go')"]
  cmd = "go build -o ./bin/main ./cmd/main.go"
  post_cmd = []
  bin = "./bin/main"
  full_bin = ""
  args_bin = []

  include_ext = ["go", "json", "html", "tpl", "tmpl"]
  include_dir = []
  include_file = []
  
  exclude_dir = ["bin", "tmp", "logs", "docs"]
  exclude_file = []
  exclude_regex = ["\\.log"]
  exclude_unchanged = false
  
  follow_symlink = true
  log = "air.log"
  
  poll = false
  poll_interval = 1000 # ms
  
  delay = 1000 # ms
  kill_delay = 1000 # ms

  stop_on_error = true
  send_interrupt = true
  
  rerun = false
  rerun_delay = 1000 # ms

[log]
  level = "info"
  time = true

[misc]
    clean_on_exit = true

[screen]
    clear_on_rebuild = true
    keep_scroll = false