root = "/app"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd"
  post_cmd = []
  bin = "./tmp/main"
  full_bin = "./tmp/main"
  args_bin = []
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]  
  watch_dir = ["."]

[log]
  time = true
  file = "./tmp/air.log"

[delay]
  before = 1000
  after = 1000   

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = false