version: '3.8'
name: myapp

services:
  api:
    build: .
    container_name: myapp-api
    volumes:
      - .:/app
      - /app/tmp
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - REDIS_HOST=redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    container_name: myapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./scripts/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: myapp-redis
    ports:
      - "6379:6379"
